### ISSUE TITLE
Use deployment diagram provided by C4-PlantUML

### ISSUE THREAD

**Issue by Riduidel** [structurizr/java-extensions#39]
Currently, the C4 deployment diagram uses standard PlantUML boxes.
It could be better to use the elements provided by C4-PlantUML deployment diagram type.

**Comment by toorog** [comment]
It would be very beneficial if structurizr-plantuml could generate plantuml macros only. By doing so, it would be quite easy to replace the content of these macros with whatever presentation is wanted.

e.g. instead of `rectangle "==my software system\nDescription" <<123>> as 123` generate something like `System(123,"my software system","Description")`

**Comment by simonbrowndotje** [comment]
Sounds like it could be useful ... feel free to submit a PR with another PlantUML implementation that outputs macros (copying the C4PlantUML writer would be a good starting point).

**Comment by simonbrowndotje** [comment]
I've switched the C4-PlantUML export to use the `Deployment_Node` macro (the code is not yet in this repo).

![image](https://user-images.githubusercontent.com/1009874/113672094-2b031e80-96af-11eb-8638-ab2c11d6103f.png)

**Comment by simonbrowndotje** [comment]
This has been rolled out to https://structurizr.com/dsl if you'd like to test it.
