### ISSUE TITLE
Add group support to PlantUML and Mermaid export formats

### ISSUE THREAD

**Issue by sjbanner** [structurizr/java-extensions#48]
In the [language doc](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md), the _groups_ tag indicates that it can be used under the _model_, _softwareSystem_ and _container_ blocks, but is only listed as a valid child under the _model_ and _enterprise_ tags. And when I tried using it, it has no impact on the resulting C4PlantUML (obtained with the CLI tool) for the _model_, _softwareSystem_ and _container_ usage (I didn't try at the _enterprise_ level.

For the system I am working with a single group (Boundary C4-PlantUML element) of components within a container, vastly improved the layout of the diagram improving both readability and understandability.

**Comment by simonbrowndotje** [comment]
The group functionality is relatively new, and not yet supported by the export formats. I've transferred the issue to the `java-extensions` repo, and renamed it.

**Comment by simonbrowndotje** [comment]
Since there are some other features missing from some of the diagram export formats, I'm taking the opportunity to merge them all together with a view to sharing code to get the feature sets consistent. Here's what I have so far for group support with the PlantUML exporters.

![image](https://user-images.githubusercontent.com/1009874/113671589-72d57600-96ae-11eb-94e4-6ad2f3c24734.png)

![image](https://user-images.githubusercontent.com/1009874/113671619-841e8280-96ae-11eb-9230-1d96143e5f9d.png)

**Comment by simonbrowndotje** [comment]
This has been rolled out to https://structurizr.com/dsl if you'd like to test it.

**Comment by sjbanner** [comment]
Yep, it looks good in the render there. Still not in the PlantUML formats, but I saw your comment above that support for those formats is relatively new, so I assume it will come as that support matures.

Thanks.

**Comment by sjbanner** [comment]
Odd, it's there now. But I didn't see it when I tried 15 minutes ago.
